version: '3.8'
services:
  frontend:
    restart: unless-stopped
    build: ./frontend
    ports:
      - 5000:5000
    volumes:
      - ./frontend:/usr/src/app
    # TOOD : Link station to frontend
    # links:
    #   - station
    tty: true
    stdin_open: true
