version: '3.8'
services:
  robot:
    restart: unless-stopped
    build: ./robot
    volumes:
      - ./robot:/root/catkin_ws/src
    tty: true
    stdin_open: true
  station:
    restart: unless-stopped
    build: ./station
    volumes:
      - ./station:/root/catkin_ws/src
    links:
      - robot
    tty: true
    stdin_open: true
