export enum Step {
  CycleNotStarted = "cycleNotStarted",
  CycleReadyInWaitingMode = "cycleReadyInWaitingMode",
  CycleStartedAndDisplayAllConsumptions = "cycleStartedAndDisplayAllConsumptions",
  ToResistanceStation = "toResistanceStation",
  CalculateResistance = "calculateResistance",
  ToControlPanel = "toControlPanel",
  DecodeControlPanel = "decodeControlPanel",
  ToFirstPuck = "toFirstPuck",
  GrabFirstPuck = "grabFirstPuck",
  toFirstCorner = "toFirstCorner",
  ToSecondPuck = "toSecondPuck",
  GrabSecondPuck = "grabSecondPuck",
  toSecondCorner = "toSecondCorner",
  ToLastPuck = "toLastPuck",
  GrabLastPuck = "grabLastPuck",
  ToLastCorner = "toLastCorner",
  FinalRobotPlacementInGreenSquare = "finalRobotPlacementInGreenSquare",
  CycleEndedAndRedLedOn = 'cycleEndedAndRedLedOn',
}
