export enum Step {
  CycleNotStarted = "cycleNotStarted",
  CycleReady = "cycleReady",
  CycleStarted = "cycleStarted",
  ToResistanceStation = "toResistanceStation",
  CalculateResistance = "calculateResistance",
  ToControlPanel = "toControlPanel",
  DecodeControlPanel = "decodeControlPanel",
  ToFirstPuck = "toFirstPuck",
  GrabFirstPuck = "grabFirstPuck",
  toFirstCorner = "toFirstCorner",
  ToSecondPuck = "toSecondPuck",
  GrabSecondPuck = "grabSecondPuck",
  toSecondCorner = "toSecondCorner",
  ToLastPuck = "toLastPuck",
  GrabLastPuck = "grabLastPuck",
  ToLastCorner = "toLastCorner",
  FinalRobotPlacement = "finalRobotPlacement",
  CycleEnded = 'cycleEnded',
}
