const SOCKET_RESISTANCE = 'SOCKET_RESISTANCE';
const SOCKET_ROBOT_CONSUMPTION = 'SOCKET_ROBOT_CONSUMPTION';
const SOCKET_PUCK_COLORS = 'SOCKET_PUCK_COLORS';

export { SOCKET_RESISTANCE, SOCKET_ROBOT_CONSUMPTION, SOCKET_PUCK_COLORS };
