const SOCKET_RESISTANCE = 'SOCKET_RESISTANCE';
const SOCKET_ROBOT_CONSUMPTION = 'SOCKET_ROBOT_CONSUMPTION';
const SOCKET_PUCK_COLORS = 'SOCKET_PUCK_COLORS';
const SOCKET_PUCK_FIRST_CORNER = 'SOCKET_PUCK_FIRST_CORNER';

export {
  SOCKET_RESISTANCE,
  SOCKET_ROBOT_CONSUMPTION,
  SOCKET_PUCK_COLORS,
  SOCKET_PUCK_FIRST_CORNER,
};
