const SOCKET_ROBOT_CONSUMPTION = 'SOCKET_ROBOT_CONSUMPTION';
const SOCKET_RESISTANCE_AND_PUCK_COLORS = 'SOCKET_RESISTANCE_AND_PUCK_COLORS';
const SOCKET_PUCK_FIRST_CORNER = 'SOCKET_PUCK_FIRST_CORNER';
const SOCKET_ADD_PLANNED_TRAJECTORY_COORDINATE =
  'SOCKET_ADD_PLANNED_TRAJECTORY_COORDINATE';
const SOCKET_ADD_REAL_TRAJECTORY_COORDINATE =
  'SOCKET_ADD_REAL_TRAJECTORY_COORDINATE';

export {
  SOCKET_ROBOT_CONSUMPTION,
  SOCKET_RESISTANCE_AND_PUCK_COLORS,
  SOCKET_PUCK_FIRST_CORNER,
  SOCKET_ADD_PLANNED_TRAJECTORY_COORDINATE,
  SOCKET_ADD_REAL_TRAJECTORY_COORDINATE,
};
