#!/usr/bin/env python3

import rospy
from std_msgs.msg import String, Bool
from geometry_msgs.msg import PoseStamped

from commands.chain_of_commands_factory import ChainOfCommandsFactory
from commands.command_builder import CommandBuilder
from commands.step import Step


def create_chain_of_commands():
    steps = [Step.MOVE_ROBOT_TO_NEXT_PUCK, Step.GRIP_PUCK, Step.MOVE_ROBOT_TO_NEXT_CORNER, Step.RELEASE_PUCK, Step.MOVE_ROBOT_TO_NEXT_PUCK, Step.GRIP_PUCK, Step.MOVE_ROBOT_TO_NEXT_CORNER, Step.RELEASE_PUCK, Step.MOVE_ROBOT_TO_NEXT_PUCK, Step.GRIP_PUCK, Step.MOVE_ROBOT_TO_NEXT_CORNER, Step.RELEASE_PUCK]

    command_builder = CommandBuilder()
    chain_of_commands_factory = ChainOfCommandsFactory(command_builder)

    return chain_of_commands_factory.create(steps)

def initialize_handled_data():
    return {"puck_colors": ["red", "blue", "green"],
     "corners": ["C", "B", "A"],
      "movement_vectors_string_pub": rospy.Publisher('movement_vectors_string', String, queue_size=1),
      "goal_pub":rospy.Publisher('move_base_simple/goal', PoseStamped, queue_size=1),
      "calculate_pucks_pub": rospy.Publisher("calculate_pucks", Bool, queue_size=1)  }

def controller():
    commands = create_chain_of_commands()
    handled_data = initialize_handled_data()
    for command in commands:
        handled_data = command.execute(handled_data)


if __name__ == '__main__':
    try:
        rospy.init_node('controller', anonymous=True)
        controller()
    except rospy.ROSInterruptException:
        pass
