name: Coverage

on:
  push:
    branches:
      # TODO : use develop
      - feature/codecov
  pull_request:
    branches:
      # TODO : use develop
      - feature/codecov

jobs:
  cover-scripts:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: scripts
    strategy:
      matrix:
        node-version: [ 15.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build -t scripts .
      - name: Run tests with coverage
        run: docker run scripts pytest --cov=./
      - name: Upload coverage to codecov
        env:
          CI: "true"
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: curl -s https://codecov.io/bash | bash -s -- -t $CODECOV_TOKEN