name: Coverage

on:
  push:
    branches:
      # TODO : use develop
      - feature/codecov
  pull_request:
    branches:
      # TODO : use develop
      - feature/codecov

jobs:
  cover-scripts:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: scripts
    strategy:
      matrix:
        node-version: [ 15.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build -t scripts .
      - name: Setup CI env
        env:
          CI: "true"
        run: docker run scripts /bin/bash -c "bash <(curl -s https://codecov.io/env)"
      - name: Run tests with coverage
        run: docker run scripts pytest --cov=./ --cov-report=xml:/.coverage.xml
      - name: Upload code coverage to codecov
        env:
          CI: "true"
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: docker run scripts /bin/bash -c "bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN -F scripts -f coverage.xml"
