name: Coverage

on:
  push:
    branches:
      # TODO : use develop
      - feature/codecov
  pull_request:
    branches:
      # TODO : use develop
      - feature/codecov

jobs:
  cover-scripts:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: scripts
    strategy:
      matrix:
        node-version: [ 15.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build -t scripts .
      - name: Run tests with coverage
        run: docker run -i -v $PWD/output:/output scripts python -m pytest --cov=./ --cov-report xml:/output/coverage.xml
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: output/coverage.xml
          flags: scripts
