name: Coverage

on:
  push:
    branches:
      # TODO : use develop
      - feature/codecov
  pull_request:
    branches:
      # TODO : use develop
      - feature/codecov

jobs:
  cover-scripts:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: scripts
    strategy:
      matrix:
        node-version: [ 15.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build -t scripts .
      - name: Run tests with coverage
        run: docker run scripts pytest --cov=./
      - name: Setup codecov env
        run: CODECOV_ENV=`bash <(curl -s https://codecov.io/env)`
      - name: Upload code coverage to codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: docker run scripts codecov -t $CODECOV_TOKEN -e $CODECOV_ENV -F scripts
