name: Robot CI

on:
  push:
    branches:
      - develop
    paths:
      - 'robot/**'
  pull_request:
    branches:
      - develop
    paths:
      - 'robot/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker-compose.yml
    steps:
      - uses: actions/checkout@v2
      - name: Build docker images
        run: docker-compose build robot
      - name: Install dependencies
        run: |
          docker-compose run robot python -m pip install --upgrade pip
          docker-compose run robot pip install -r requirements.txt
      - name: Lint scripts
        run: docker-compose run robot pylint samples tests
      - name: Test scripts
        run: docker-compsoe run pytest tests
