name: Robot CI

on:
  push:
    branches:
      - develop
    paths:
      - 'robot/**'
  pull_request:
    branches:
      - develop
    paths:
      - 'robot/**'

defaults:
  run:
    working-directory: robot

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker-compose.yml
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build -t robot .
      - name: Install dependencies
        run: |
          docker run robot python -m pip install --upgrade pip
          docker run robot pip install -r requirements.txt
      - name: Lint scripts
        run: docker run robot pylint main
      - name: Test scripts
        run: docker run robot pytest tests
