name: Scripts CI

on:
  push:
    branches:
      - develop
    paths:
      - 'scripts/**'
  pull_request:
    branches:
      - develop
    paths:
      - 'scripts/**'

defaults:
  run:
    working-directory: scripts

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build -t scripts .
      - name: Lint application
        # TODO : Can we just write this in a single command?
        run: |
          docker run scripts pylint capture
          docker run scripts pylint detection
          docker run scripts pylint mapping
          docker run scripts pylint processing
          docker run scripts pylint samples
          docker run scripts pylint tests
      - name: Test application
        run: docker run scripts pytest /tests
