name: Station CI

on:
  push:
    branches:
      - develop
    paths:
      - 'objectives/**'
  pull_request:
    branches:
      - develop
    paths:
      - 'objectives/**'

defaults:
  run:
    working-directory: objectives

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build -t objectives .
      - name: Lint application
        run: docker run objectives pylint src
      - name: Test application
        run: docker run objectives pytest
